@startgantt

printscale daily zoom 3

Project starts the 3rd of January 2022

[Implementierungsphase] starts 2022-01-03 and ends 2022-02-04
[Implementierungsphase] is colored in lightgreen
[Setup Git Repo] starts 2022-01-06 and ends 2022-01-10
[Implementierungsplan erstellen] starts 2022-01-10 and lasts 2 days
[Model Interfaces und Classes] starts 2022-01-03 and ends 2022-01-16
[Model Interfaces und Classes] is colored in lightblue
[interface Project] starts 2022-01-03
[interface Table] starts 2022-01-03
[interface ProjectSkeleton] starts 2022-01-03
[interface ProjectTemplate] starts 2022-01-03
[interface Settings] starts 2022-01-03
[interface User] starts 2022-01-03
[class SimpleUser] starts at [interface User]'s end
[class UIElement] starts 2022-01-03
[enum class UIElementType] starts 2022-01-03
[interface Table] starts 2022-01-03
[interface TableLayout] starts 2022-01-03
[interface Row] starts 2022-01-03
[class ArrayListRow] starts at [interface Row]'s end
[class RowMetaData] starts 2022-01-03
[interface Notification] starts 2022-01-03
[class TimeNotification] starts at [interface Notification]'s end

[Entities] starts 2022-01-06 and ends 2022-01-11
[Entities] is colored in lightblue
[class GraphEntity] starts 2022-01-06 and ends 2022-01-07
[class GraphTemplateEntity] starts 2022-01-07
[class MissingSlotEntity] starts 2022-01-09
[class NotificationEntity] starts 2022-01-07
[class ProjectData] starts 2022-01-06
[class ProjectEntity] starts 2022-01-06
[class ProjectSkeletonEntity] starts 2022-01-06
[class ProjectTemplateEntity] starts 2022-01-07
[class ProjectUserMap] starts 2022-01-07
[class RowEntity] starts 2022-01-06
[class ProjectSettingEntity] starts 2022-01-09
[class ProjectSettingEntity] starts 2022-01-09
[class UIElementMap] starts 2022-01-09

[DAOs] starts 2022-01-08 and ends 2022-01-15
[DAOs] is colored in lightblue

[Type Converters] starts 2022-01-05 and ends 2022-01-13
[Type Converters] is colored in lightblue

[Other Database Tasks] starts 2022-01-03 and ends 2022-01-20
[Other Database Tasks] is colored in lightblue
[class AppDataBase] starts 2022-01-03

/'Repository====================================================================================='/

[Repository Interfaces und Classes] starts 2022-01-13 and ends 2022-01-18
[Repository Interfaces und Classes] is colored in lightblue

[View Model Interface] starts 2022-01-13 and ends 2022-01-18
[View Model Interface] is colored in lightblue
    [class PostHandler] starts 2022-01-13 and ends 2022-01-13
    [class CommandFactory] starts 2022-01-13 and ends 2022-01-13
    [class ProjectHandler] starts 2022-01-13 and ends 2022-01-13

    [CommunicationClasses] starts 2022-01-13
    [CommunicationClasses] is colored in lightblue
        [class DataType] starts 2022-01-13 and ends 2022-01-13
        [class DotSize] starts 2022-01-13 and ends 2022-01-13
        [class LineType] starts 2022-01-13 and ends 2022-01-13
        [class Time] starts 2022-01-13 and ends 2022-01-13
        [class Notification] starts at [class Time]'s end
        [class Member] starts 2022-01-13 and ends 2022-01-13
        [class Row] starts 2022-01-13 and ends 2022-01-13
        [class Button] starts 2022-01-13 and ends 2022-01-13
        [class Column] starts at [class DataType]'s end
        [class Graph] starts 2022-01-13 and ends 2022-01-13
        [class LineChart] starts at [class Graph]'s end
            [class LineChart] starts at [class DotSize]'s end
            [class LineChart] starts at [class LineType]'s end
            [class LineChart] starts at [class Column]'s end
        [class PieChart] starts at [class Graph]'s end
        [class ProjectPreview] starts 2022-01-13 and ends 2022-01-13
        [class Project] starts at [class Button]'s end
            [class Project] starts at [class Notification]'s end
            [class Project] starts at [class Member]'s end
            [class Project] starts at [class PieChart]'s end
            [class Project] starts at [class LineChart]'s end
            [class Project] starts at [class Row]'s end
    [CommunicationClasses] ends at [class Project]'s end

[CommandCenter] starts 2022-01-13 and ends 2022-01-13
[CommandCenter] is colored in lightblue
    [class CommandUtility] starts 2022-01-13 and ends 2022-01-13
    [class CommandInbox] starts 2022-01-13 and ends 2022-01-13

    [Commands] starts 2022-01-13 and ends 2022-01-13
    [Commands] is colored in lightblue
        [class ProjectCommand] starts 2022-01-13 and ends 2022-01-13
        [class IllegalOperationException] starts 2022-01-13 and ends 2022-01-13
        [class CommandWrapper] starts 2022-01-13 and ends 2022-01-13
        [class AddRow] starts 2022-01-13 and ends 2022-01-13
        [class DeleteRow] starts 2022-01-13 and ends 2022-01-13
        [class DeleteColumn] starts 2022-01-13 and ends 2022-01-13
        [class AddColumn] starts 2022-01-13 and ends 2022-01-13
        [class SetCell] starts 2022-01-13 and ends 2022-01-13
        [class SetAdmin] starts 2022-01-13 and ends 2022-01-13
        [class AddUser] starts 2022-01-13 and ends 2022-01-13
        [class RemoveUser] starts 2022-01-13 and ends 2022-01-13
        [class CreateGraph] starts 2022-01-13 and ends 2022-01-13
        [class SetCalculationFunction] starts 2022-01-13 and ends 2022-01-13
        [class SetTransformationFunctionCompostition] starts 2022-01-13 and ends 2022-01-13
        [class SetSetting] starts 2022-01-13 and ends 2022-01-13
        [class SetProjectName] starts 2022-01-13 and ends 2022-01-13
        [class SetProjectDesign] starts 2022-01-13 and ends 2022-01-13
        [class SetWallpaper] starts 2022-01-13 and ends 2022-01-13
        [class SetNotification] starts 2022-01-13 and ends 2022-01-13
        [class DeleteNotification] starts 2022-01-13 and ends 2022-01-13
        [class SetUIElement] starts 2022-01-13 and ends 2022-01-13
        [class RequestOldData] starts 2022-01-13 and ends 2022-01-13
        [class SetIsOnlineProject] starts 2022-01-13 and ends 2022-01-13
        [class CreateProject] starts 2022-01-13 and ends 2022-01-13

    [UpToDater] starts 2022-01-13 and ends 2022-01-13
    [UpToDater] is colored in lightblue
        [class OldDataFetcher] starts 2022-01-13 and ends 2022-01-13

legend
    Aufgaben, die vor dem 10. Januar 2022 abgeschlossen sind,
     sind zum Zeitpunkt der Erstellung dieses Diagramms bereits abgeschlossen.
end legend



@endgantt