package com.pseandroid2.dailydataserver.onlineproject;

import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/**
 * interface for "talking" about old data
 * the user can post request for old Data und can get request for a project to help other participants
 */
@RestController
@RequestMapping("/OnlineDatabase/request")
public class FetchRequestController {

    /**
     *  Saves a request for old Data by the user.
     *  Another participant can fetch such requests.
     *
     * @param user the user, who needs old Data, generated by the server.
     * @param token the token, to verify the user, provided by the client
     * @param requestInfo the request, which is usefull for another user. Contains information for recommended Delta, provided by the client
     * @param projectID the project to which the request belongs, provided by the client
     */
    @PostMapping("/need/{id}")
    public void demandOldData(@RequestAttribute String user, @RequestHeader String token, @RequestParam String requestInfo, @PathVariable("id") long projectID){

    }

    /**
     *
     * @param user the user, who wants the requests, generated by the server.
     * @param token  the token, to verify the user, provided by the client
     * @param projectId the project, to which the requests belong, provided by the client
     * @return a list of FetchRequests, which contains the user, who needs the delta, the project and the requestInfo.
     */

    @GetMapping("/provide/{id}")
    public List<FetchRequest> getFetchRequests(@RequestAttribute String user, @RequestHeader String token, @PathVariable("id") long projectId){

      return new ArrayList<FetchRequest>();
    }
}
