package com.pseandroid2.dailydataserver.onlineproject;

import com.pseandroid2.dailydataserver.RequestParameter;
import com.pseandroid2.dailydataserver.onlineproject.requestParameters.projectParticipantsController.RemoveUserParameter;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * All interactions with usermanagement happens here. Provides functions to add and remove users and create new projects.
 * #TODO Testen, JavaDoc
 */
@RestController
@RequestMapping("/OnlineDatabase")
public class ProjectParticipantsController {

    /**
     * Adds a user to a project.
     *
     * @param user      the user who wants to join the project. generated by the server.
     * @param projectId the project, where the user wants to participate.  provided by the client.
     * @return false, if the project is full or the user can not participate.
     */
    @PostMapping("/addUser/{id}")
    public boolean addUser(@RequestAttribute String user, @PathVariable("id") long projectId, @RequestBody RequestParameter param) {
        return true;
    }

    /**
     * Removes a user from a project. A user can remove himself.
     *
     * @param user         the user who wants to remove someone, generated by the server.
     * @param projectId    the project, where the userToRemove should be removed from.
     * @return true, if the user is removed, false if it was not possible.
     */
    @DeleteMapping("/removeUser/{id}")
    public boolean removeUser(@RequestAttribute String user, @PathVariable("id") long projectId, @RequestBody RemoveUserParameter param) {
        return true;
    }

    /**
     * Adds a new project. The user, who initializes the project is the admin.
     *
     * @param user  who wants to create a project.
     * @return the projectId for the new project.
     */
    @PostMapping("/newProject")
    public long addProject( @RequestAttribute String user, @RequestBody RequestParameter param) {
        return 0;
    }
}
