skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

package ConverterLogic {

	' Wandelt Commands in/von JSON um
	class CommandConverter <<singleton>>{
		..Converter..
		+CommandToJSON(Command): JSON
		+JSONToCommand(JSON): Command
	}
}