skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

package ServerConnection {
    class ServerManager <<singleton>>{
    - RESTController restController
    - 
    }


	' Kuemmert sich um die Connection mit unserem Server
	class RESTAPI <<singleton>>{
	-ServerIP : String

	void connectToServer()

    WorkToken RequestToServer.saveDelta()
    WorkToken RequestToServer.getLatestDelta()

    WorkToken RequestToServer.addUser()
    WorkToken RequestToServer.removeUser()

    WorkToken RequestToServer.getOldData()
    
    WorkToken RequestToServer.showPosts()
    WorkToken RequestToServer.displayPost()
    
    WorkToken RequestToServer.downloadTemplate()
	}

    ServerManager "1" *-down- "1" RESTAPI: contains
}