skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

package ServerConnection {
	' Kuemmert sich um die Connection mit unserem Server
	class RESTController <<Singleton>>{
	-ServerIP : String

	void connectToServer();

	}
}