@startuml
skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

package RemoteDataSource {

!include RemoteDataSourceAPI\RemoteDataSourceAPI.puml!RemoteDataSourceAPI

!include UserManager\UserManager.puml!UserManager
!include CommandLogic\CommandLogic.puml!CommandLogic
!include ServerConnection\ServerConnection.puml!ServerConnection
}




' Aggregationen:

' RemoteDatSourceAPI ist eine _Fassade_ -> Muss als einzige Klasse vom Repository aufgerufen werden
RemoteDataSourceAPI "1" *-- "1" UserAccount: contains
RemoteDataSourceAPI "1" *-- "1" RESTController: contains
RemoteDataSourceAPI "1" *-- "1" CommandController: contains

' Commands muessen an den Server gesendet werden
CommandController "1" *-left- "1" RESTController: contains



class FirebaseAPI {
}

' Firebase conntection
FirebaseManager "1" .right.> "1" FirebaseAPI: uses


package Server {
	
}

' Serverconnection
RESTController "1" .left.> "1" Server



@enduml