@startuml
skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

package RemoteDataSource {

!include RemoteDataSourceAPI\RemoteDataSourceAPI.puml!RemoteDataSourceAPI

!include UserManager\UserManager.puml!UserManager
!include ConverterLogic\ConverterLogic.puml!ConverterLogic
!include ServerConnection\ServerConnection.puml!ServerConnection
}




' Aggregationen:

' RemoteDatSourceAPI ist eine _Fassade_ -> Muss als einzige Klasse vom Repository aufgerufen werden
RemoteDataSourceAPI "1" *-- "1" UserAccount: contains
RemoteDataSourceAPI "1" *-- "1" ServerManager: contains
RemoteDataSourceAPI "1" *-- "1" ConverterLogic: contains


class FirebaseAPI {
}

' Firebase conntection
FirebaseManager "1" .down.> "1" FirebaseAPI: uses


package Server {
	
}

' Serverconnection
RESTAPI "1" .down.> "1" Server



@enduml