@startuml Methode: SendCommandsToServer
skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

RemoteDataSourceAPI -> ServerManager: call
    activate RemoteDataSourceAPI 
    activate ServerManager #D3D3D3
loop n times
    ServerManager -> RESTAPI: saveDelta(projectID, projectCommand, user)
        activate ServerManager #C0C0C0
        activate RESTAPI #A9A9A9
    RESTAPI ->  Server: saveDelta(projectID, projectCommand, user)
        activate Server #808080
    Server -> RESTAPI: answer
        deactivate Server
    RESTAPI -> ServerManager: answer
        deactivate RESTAPI
    ServerManager -> ProjectCommandQueue: addProjectCommand(projectCommand)
        activate ProjectCommandQueue #A9A9A9   
    ProjectCommandQueue -> ServerManager: return null    
        deactivate ProjectCommandQueue 
        deactivate ServerManager
end
ServerManager -> RemoteDataSourceAPI: return null
@enduml