skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

class RemoteDataSourceAPI <<fassade>> {
	- commandController: CommandController 
	- userAccount: UserAccount 
	- serverManager: ServerManager 

	----
	..UserAccount..
	+ registerUser(String eMail, String passwort): int 
	+ signInUser(String eMail, String passwort): int
	+ signOut(): int
	..UserDetails..
	+getUserID(): String
	+getUserName(): String
	+getUserEMail(): String
	+getUserPhotoUrl(): String
	..ServerAccess..
	+isServerAccessible(): bool
	+sendCommandsToServer(List<Commands>): void
	+getDeltasFromServer(): Liste<(UploadTime, UserID, JSON)>
	+getPostsFromServer():List<Post>
	+getOldDeltaRequest(JSON)
	+uploadOldDelta(List<JSON>)
	+downloadTemplate(int templateID, enum TemplateType): JSON
	+removeUserFromProject(String User_Id_toRemove, int projectID)
}