skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

class RemoteDataSourceAPI <<fassade>> {
	- CommandController commandController
	- UserAccount userAccount
	- ServerManager serverManager
	----
	..ServerRequests..
	+ bool ServerConnectable()
	'+ String GetServerTime()
	+ String GetCommandDurationOfStayOnServer()	
	' Die Zeit, bis ein Command nach seiner Erstellung vom Server gelöscht wird. Normal 72 Stunden
	..Project Operations..
	+ int CreateOnlineProject()
	' gibt die ID des OnlineProjekts zurück
	+ String IsProjectOnline(int ProjectID)
	+ String LaunchProject(int ProjectID)
	' Startet ein online Projekt (welches schon auf dem Server war, aber nicht online ist)
	..Commands..
	+ int SaveCommandToServer(Command command, int ProjectID)
	+ List<Command> GetCommandDeltas(Timestamp startTime, int ProjectID)
    ..PostLogic..

}