skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

class RemoteDataSourceAPI <<fassade>> {
	- commandController: CommandController 
	- userAccount: UserAccount 
	- serverManager: ServerManager 
	----
	..ServerRequests..
	+ ServerConnectable(): bool
	
	+ GetCommandDurationOfStayOnServer(): String 	
	..Project Operations..
	+ CreateOnlineProject():int 
	' gibt die ID des OnlineProjekts zurück
	+ IsProjectOnline(int ProjectID): String 
	+ LaunchProject(int ProjectID): String
	' Startet ein online Projekt (welches schon auf dem Server war, aber nicht online ist)
	..Commands..
	+ SaveCommandToServer(Command command, int ProjectID): int
	+ GetCommandDeltas(Timestamp startTime, int ProjectID): List<Command> 
    ..PostLogic..

}