
@startuml

skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle



package Spring{
class HandlerInterceptorAdaper{}
class WebMvcConfigurerAdapeter{}
class JpaRepository{}
}

package Server
{

GreetingController ..> ServerGreetings: uses

!include OnlineDatabase.puml
!include PostDatabase.puml

   GeneralConfig -- LoginIntercepter
   AccessToProjectInterceptor -- GeneralConfig



    class ServerApplication <<SpringBootApplication>>{
        main(this:ServerApplication,args:String[])
    }
    class GeneralConfig extends WebMvcConfigurerAdapeter{
        addInterceptor()
    }
    class LoginIntercepter extends HandlerInterceptorAdaper {
        preHandle():boolean
    }


 class ServerGreetings{
  +greeting():boolean
 }

 class GreetingController{
 + greets():boolean
 }

  class Tupel <T,U> {
      - first: T
      - second: U
  }
}

Tupel .. DeltaRepository : uses <
Tupel .. ProjectParticipantsRepository : uses <

LoginIntercepter ... Firebase : uses >
package Firebase {
}


@enduml