@startuml

skinparam monochrome true
skinparam shadowing false
skinparam genericDisplay old
skinparam classAttributeIconSize 0
hide circle

participant "ADD_ROW: ProjectCommand" as addCommand
participant "test" as row

[-> addCommand : execute()
activate addCommand



@enduml